# Semana 3

In [2]:
import numpy as np
a=np.array([1,2,3])
print(a)
b=np.array([(1,2,3),(4,5,6)])
print(b)

[1 2 3]
[[1 2 3]
 [4 5 6]]


In [15]:
#Arreglo 3 dimenciones
c=np.array([[(1,2,3),(4,5,6)],[(7,8,9),(10,11,12)]])
print(c)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [16]:
x=np.array([(1,2,3),(4,5,6)])
print(x.data)
type(x)

numpy.ndarray

# Numpy en lugar de estructuras

In [12]:
import sys
S=range(1000)
print(sys.getsizeof(5)*len(S))

D=np.arange(1000)
print(D.size*D.itemsize)

28000
4000


In [20]:
import time
SIZE=1000000
L1=range(SIZE)
L2=range(SIZE)
A1=np.arange(SIZE)
A2=np.arange(SIZE)

start=time.time()
result=[x+y for x,y in zip(L1,L2)]
print((time.time()-start)*1000)

start=time.time()
result=A1+A2
print((time.time()-start)*1000)

249.55224990844727
26.003122329711914


## Ejercicios

In [23]:
import time 
import numpy as np

list1=[i for i in range(10000)]
list2=[i for i in range(10000)]
inicio=time.time()
dot=0
for i,j in zip(list1,list2):
    dot+=i*j
round(time.time()-inicio,5)

0.00552

# Con un byte

In [24]:
import time
import numpy as np

arr1=np.array([i for i in range(10000)])
arr2=np.array([i for i in range(10000)])
inicio=time.time()
arr=np.dot(arr1,arr2)
round(time.time()-inicio,5)

0.0382

In [25]:
import time
import numpy as np

arr1=np.array([i for i in range(10000)])
arr2=np.array([i for i in range(10000)])
inicio=time.time()
arr=concatenate((arr1,arr2),axis=0)
round(time.time()-inicio,5)

NameError: name 'concatenate' is not defined

# 2

In [26]:
lista=[25,12,15,66,12.5]
vector=np.array(lista)
print(vector)

[25.  12.  15.  66.  12.5]


In [27]:
print(vector[3])
print(vector[1:4])
print(vector[1:])
print(vector[:4])
print(vector[:])

66.0
[12. 15. 66.]
[12.  15.  66.  12.5]
[25. 12. 15. 66.]
[25.  12.  15.  66.  12.5]


In [28]:
print("- vector original")
print(vector)

- vector original
[25.  12.  15.  66.  12.5]


In [29]:
print("- Sumarle 1 a cada elemento del vector")
print(vector+1)
print("- Multiplicar por 2 a cada elemento del vector")
print(vector*2)
print("- multiplicar por 5 a cada elemento del vector")
print(vector*5)

- Sumarle 1 a cada elemento del vector
[26.  13.  16.  67.  13.5]
- Multiplicar por 2 a cada elemento del vector
[ 50.  24.  30. 132.  25.]
- multiplicar por 5 a cada elemento del vector
[125.   60.   75.  330.   62.5]


In [30]:
print("-suma de todos los vectores")
print(np.sum(vector)) #suma de todos los elementos del vector

-suma de todos los vectores
130.5


In [31]:
print("- matriz creada con np.zeros")
print(np.zeros((3,4))) #matriz de 3 filas y 4 columnas

- matriz creada con np.zeros
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [32]:
print("- matriz creada con np.ones")
print(np.ones((3,4))) #matriz de 3 filas y 4 columnas

- matriz creada con np.ones
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [34]:
matriz_unos=np.ones((3,4))
print(matriz_unos)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


## Ejercicios

In [50]:
# Crear una matriz de 4x4 con valores de 0.5, utilizando import random random.radint(1,101)
matriz_random=np.random.randint(1,106,size=(5,5))
print(matriz_random)

[[ 14  12  87  72  32]
 [  6  11  87  26  25]
 [ 43 103   8  90   5]
 [ 35  99  27  19  19]
 [ 81  69   5  13  82]]


In [61]:
import numpy as np

vector_rango = np.random.randint(10, 50, size=10)
print(vector_rango)
# Invertir el vector
print("=========================================================================")
print(vector_rango[::-1])


[28 26 15 25 15 39 37 41 10 19]
[19 10 41 37 39 15 25 15 26 28]


In [72]:
# Tomar el tiempo d ela multiplicacion de las siguientes dimenciones:10x10, 100x100, 1000x1000 . Guardar los tiempos en un archivo de texto
import time
import numpy as np

archivo_tiempo = open("tiempos.txt", "w")
dimensiones = [10, 100, 1000]
for dim in dimensiones:
    matriz1=np.random.randint(1,100,size=(dim,dim))
    matriz2=np.random.randint(1,100,size=(dim,dim))
      inicio = time.time()
    matriz = np.dot(matriz1, matriz2)
    tiempo = round(time.time() - inicio, 5)

    archivo_tiempo.write(f"Dimensiones: {dim}x{dim}, Tiempo: {tiempo} segundos\n")

# Cerrar el archivo de texto
archivo_tiempo.close()


In [73]:
import numpy as np
import time

archivo_tiempo = open("tiempos2.txt", "w")
archivo_tiempo.write("# Tomar el tiempo de la multiplicacion de las siguientes dimensiones: 10x10, 100x100, 1000x1000\n\n")

dimensiones = [10, 100, 1000]

for dim in dimensiones:
    matriz1 = np.random.randint(1, 100, size=(dim, dim))
    matriz2 = np.random.randint(1, 100, size=(dim, dim))

    inicio = time.time()
    matriz = np.dot(matriz1, matriz2)
    tiempo = round(time.time() - inicio, 5)

    archivo_tiempo.write(f"Dimensiones: {dim}x{dim}, Tiempo: {tiempo} segundos\n")

archivo_tiempo.close()
